---
title: "Psycholinguistics Quizzes"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
    css: webex.css
    includes:
      after_body: webex.js
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webex")) {
  stop("You must have the 'webex' package installed to knit HTML from this template.\n   devtools::install_github(\"dalejbarr/webex\")")
} else {
  library("webex")
}
```

This is a Web Exercise template created by the [psychology teaching team at the University of Glasgow](http://www.psy.gla.ac.ukUniversity of Glasgow), based on ideas by [Software Carpentry](https://software-carpentry.org/lessons/).

_Unfortunately, these interactive quizzes do not appear to work correctly using the Microsoft browser Explorer. Please write a letter to Bill Gates! However, they work correctly on Chrome and Firefox, and probably most other browsers (NB all university machines should have Chrome installed)_

# The dual route model

According to the d`r fitb("ual", width = "15")` r`r fitb("oute", width = "15")` model, past tense verbs are generated via either a l`r fitb("exical", width = "15")` or a g`r fitb("rammatical", width = "15")` route.

The former involves an`r fitb("alogical", width = "15")` and fr`r fitb("equency", width = "15")`-driven processes, while the latter involves co`r fitb("mputational", width = "15")` processes. The former involves the de`r fitb("clarative", width = "15")` memory system, while the latter involves the pr `r fitb("ocedural", width = "15")` memory system.

If the pr`r fitb("ocedural", width = "15")` memory system is impaired, this will result in better production of `r mcq(c("regular", answer = "irregular"))` verbs than `r mcq(c(answer = "regular", "irregular"))` verbs.

If the de`r fitb("clarative", width = "15")` memory system is impaired, this will result in better production of `r mcq(c(answer = "regular", "irregular"))` verbs than `r mcq(c("regular", answer = "irregular"))` verbs.

Which of the following is NOT characterised by by better performance on irregulars than regulars? `r mcq(c("Parkinson's", answer = "Alzheimers", "Developmental Language Disorder", "Agrammatic non-fluent Aphasia (Broca's type"))`

The term ps`r fitb("eudo", width = "15")`-regularity describes the phenomenon whereby the irregular system mimics the regular system.

`r hide("Show answers")`

According to the DUAL ROUTE model, past tense verbs are generated via either a LEXICAL or a GRAMMATICAL route.

The former involves ANALOGICAL and FREQUENCY-driven processes, while the latter involves COMPUTATIONAL processes. The former involves the DECLARATIVE memory system, while the latter involves the PROCEDURAL memory system.

If the PROCEDURAL memory system is impaired, this will result in better production of IRREGULAR verbs than REGULAR verbs.

If the DECLARATIVE memory system is impaired, this will result in better production of REGULAR verbs than IRREGULAR verbs.

Which of the following is NOT characterised by by better performance on irregulars than regulars? ALZHEIMMER'S

The term PSEUDO-regularity describes the phenomenon whereby the irregular system mimics the regular system.

`r unhide()`

# Models of morphological representation

A morpheme is the smallest unit of m`r fitb("eaning", width = "12")`. Morphemes which come at the beginning or ends of words are called a`r fitb("ffixes", width = "12")`. If a word contains more than one morpheme it is m`r fitb("ulti", width = "8")`morphemic, and if it contains only one morpheme it is m`r fitb("ono", width = "8")`morphemic.

There is some debate regarding the storage of multimorphemic words. According to a`r fitb("ffix", width = "8")`-stripping accounts, morphemes in multimorphemic words are stored separately. However, according to wh`r fitb("ole", width = "8")`-entry accounts, multimorphemic words are stored as wholes.

A variety of data support w`r fitb("hole", width = "8")`-entry accounts:

(1) Reaction Times data from production and lexical d`r fitb("ecision", width = "8")` tasks, suggest that high-frequency m`r fitb("ulti", width = "8")`MORPHEMIC forms may be stored as wholes.

(2) When all affixes are stripped away, sometimes the remaining r`r fitb("oot", width = "8")` has no independent meaning, e.g. in-EVIT-able.

A variety of data support a`r fitb("ffix", width = "8")`-stripping accounts:

(1) When we hear a word we actively seek out affixes, and activate them in our lexicons, a process known as morpho`r fitb("phonological", width = "10")` p`r fitb("arsing", width = "10")`

(2) When producing words, RTs increase as the number of a`r fitb("ffixes", width = "10")` increase.

(3) Speech errors involve m`r fitb("ovement", width = "10")` of affixes from one word to another.

Finally, some have argued that there are multiple forms of storage, with affixes being represented separately or not according to the semantic tra`r fitb("nsparency", width = "8")` and f`r fitb("requency", width = "8")` of word forms. This framework is called a h`r fitb("ybrid", width = "8")` framework.

`r hide("Show answers")`

A morpheme is the smallest unit of MEANING. Morphemes which come at the beginning or ends of words are called AFFIXES. If a word contains more than one morpheme it is MULTIMORPHEMIC, and if it contains only one morpheme it is MONOMORPHEMIC

There is some debate regarding the storage of multimorphemic words. According to AFFIX-stripping accounts, morphemes in multimorphemic words are stored separately. However, according to WHOLE-entry accounts, multimorphemic words are stored as wholes.

A variety of data support WHOLE-entry accounts:

(1) Reaction Times data from production and lexical DECISION tasks, suggest that high-frequency MULTIMORPHEMIC forms may be stored as wholes.

(2) When all affixes are stripped away, sometimes the remaining ROOT has no independent meaning, e.g. in-EVIT-able.

A variety of data support AFFIX-stripping accounts:

(1) When we hear a word we actively seek out affixes, and activate them in our lexicons, a process known as morphoPHONOLOGICAL PARSING

(2) When producing words, RTs increase as the number of AFFIXES increase.

(3) Speech errors involve MOVEMENT of affixes from one word to another.

Finally, some have argued that there are multiple forms of storage, with affixes being represented separately or not according to the semantic TRANSPARENCY and FREQUENCY of word forms. This framework is called a HYBRID framework.

`r unhide()`

# The lexicon

Many but not all words are stored in semantic hierarchies with three levels, e.g. Furniture > Chair > Stool, Plant > Tree > Sycamore. The middle level is called the b`r fitb(answer = "asic", width = "10")` level. Words which exist at the same level (e.g. chair/table/bookshelf, bush/tree/flower) are called co`r fitb(answer = "hyponyms", width = "10")` or co`r fitb(answer = "ordinates", width = "10")`. The words are said to belong to the same s`r fitb(answer = "emantic", width = "8")` f`r fitb(answer = "ield", width = "10")`. Words at a higher level are called hyp`r fitb(answer = "eronyms", width = "10")` or sup`r fitb(answer = "erordinates", width = "10")`, while words at a lower level are called hyp`r fitb(answer = "onyms", width = "10")` or sub`r fitb(answer = "ordinates", width = "10")`. Words in the middle (the b`r fitb(answer = "asic", width = "10")` level) are more strongly represented in memory: they are easier to v`r fitb(answer = "isualise", width = "10")` and more rapidly n`r fitb(answer = "amed", width = "10")`. There are also links between words which tend to co-occur. Words tend to occur next to each other are called co`r fitb(answer = "llocations", width = "10")`, and words which tend to co-occur in the same chunk (phrase or sentence), but not next to each other are sometimes called ass`r fitb(answer = "ociates", width = "10")`

In word association tasks the most common response is `r mcq(c("superordinates", "subordinates", answer = "coordinates", "collocations/associates"))`, followed by `r mcq(c("superordinates", "subordinates", "coordinates", answer = "collocations/associates"))`. Word association reponses of children with Developmental Language Disorders is characterised by `r mcq(c("more", answer = "fewer"))` semantic relationships, e.g. superordinates. 

Blending errors, e.g. expect + suppose -> suppose, demonstrate (a) p`r fitb(answer = "arallel", width = "10")` a`r fitb(answer = "ctivation", width = "10")`, (b) activation across do`r fitb(answer = "mains", width = "10")`, (c) the existence of a lexical m `r fitb(answer = "onitor", width = "10")` which minimises the possibility of nonword errors.

T`r fitb(answer = "ip", width = "8")`-o`r fitb(answer = "f", width = "8")`-t`r fitb(answer = "he", width = "8")`-t`r fitb(answer = "ongue", width = "8")` studies demonstrate that phonological representations may be p`r fitb(answer = "artially", width = "8")`-activated. The b`r fitb(answer = "athtub", width = "8")` effect refers to phenomenon whereby the beginnings and endings of words are more strongly represented.

`r hide("Show answers")`

Many but not all words are stored in semantic hierarchies with three levels, e.g. Furniture > Chair > Stool, Plant > Tree > Sycamore. The middle level is called the BASIC level. Words which exist at the same level (e.g. chair/table/bookshelf, bush/tree/flower) are called COHYPONYMS or COORDINATES. The words are said to belong to the same SEMANTIC FIELD. Words at a higher level are called HYPERONYMS or SUPERORDINATES, while words at a lower level are called HYPONYMS or SUBORDINATES. Words in the middle (the BASIC level) is more strongly represented in memory: they are easier to VISUALISE and more rapidly NAMED. There are also links between words which tend to co-occur. Words tend to co-occur are called COLLOCATIONS, and words which tend to co-occur in the same chunk (phrase or sentence), but not next to each other are sometimes called ASSOICATES.

In word association tasks the most common response is COORDINATES, followed by COLLOCATIONS/ASSOCIATES. Word association reponses of children with Developmental Language Disorders is characterised by FEWER semantic relationships, e.g. superordinates. 

Blending errors, e.g. expect + suppose -> suppose, demonstrate (a) PARALLEL ACTIVATION, (b) activation across DOMAINS, (c) the existence of a lexical MONITOR which minimises the possibility of nonword errors.

TIP-OF-THE TONGUE studies demonstrate that phonological representations may be PARTIALLY activated. The BATHTUB effect refers to phenomenon whereby the beginnings and endings of words are more strongly represented.

`r unhide()`

# Word production

According to the TWO-STAGE model, there are two levels between c`r fitb(answer = "oncept", width = "10")`  and art`r fitb(answer = "iculation", width = "10")` : the lem`r fitb(answer = "ma", width = "10")`  and l`r fitb(answer = "exeme", width = "10")`  level. The l`r fitb(answer = "emma", width = "10")`  level contains sem`r fitb(answer = "antic", width = "10")`  and s`r fitb(answer = "yntactic", width = "10")`  information which is modality-`r fitb(answer = "general", width = "10")`. For example it may contain information about grammatical g`r fitb(answer = "ender", width = "10")`, arg`r fitb(answer = "ument", width = "10")` str`r fitb(answer = "ucture", width = "10")`  and how to use the word in a sentence (sub`r fitb(answer = "categorisation", width = "10")`) . The lex`r fitb(answer = "eme", width = "10")`  level contains modality-s`r fitb(answer = "pecific", width = "10")`  information, e.g. information about the word's orth`r fitb(answer = "ography", width = "10")`  and ph`r fitb(answer = "onology", width = "10")` .

According to the picture-word int`r fitb(answer = "erference", width = "10")`  paradigm, a semantic competitor results in `r fitb(answer = "interference", width = "10")`  while a phonological competitor results in early `r fitb(answer = "interference", width = "10")` , but late f`r fitb(answer = "acilitation", width = "10")` . This demonstrates the separation of the lem`r fitb(answer = "ma", width = "10")`  and l`r fitb(answer = "exeme", width = "10")`  levels. The phenomenon whereby errors tend to result in words rather than non-words is called the l`r fitb(answer = "exicality", width = "10")` effect, and suggests the existence of a word-m`r fitb(answer = "onitoring", width = "10")`  system.

`r hide("Show answers")`

According to the TWO-STAGE model, there are two levels between CONCEPT and ARTICUATION: the LEMMA and LEXEME level. The LEMMA level contains SEMANTIC and SYNTACTIC information which is MODALITY-GENERAL. For example it may contain information about grammatical GENDER, ARGUMENT STRUCTURE and how to use the word in a sentence (SUBCATEGORISATION). The LEXEME level contains MODALITY-SPECIFIC information, e.g. information about the word's ORTHOGRAPHY and PHONOLOGY.

According to the PICTURE-WORD INTERFERENCE paradigm, a semantic competitor results in INTERFERENCE while a phonological competitor results in early INTERFERENCE, but late FACILITATION. This demonstrates the separation of the LEMMA and LEXEME levels. The phenomenon whereby errors tend to result in words rather than non-words is called the LEXICALITY effect, and suggests the existence of a word-MONITORING system.

`r unhide()`

# Word comprehension.

According to a`r fitb(answer = "utonomous", width = "10")` models, bottom-up processes precede top-down processes, while according to i`r fitb(answer = "nteractive", width = "10")` models, both types of processes interact with each other.

Studies of phoneme recognition identify cat`r fitb(answer = "egorical", width = "10")` p`r fitb(answer = "erception", width = "10")` find that mbiguous phonemes presented in isolation are assumed to belong to a discrete category. This phenomenon is assumed to reflect `r mcq(c("top down", answer = "bottom up"))` processing. Ph`r fitb(answer = "onemic", width = "10")` r`r fitb(answer = "estoration", width = "10")` referrs to the phenomenon whereby noisy phonetic material (a cough or white noise) takes on a phonetic identity when inserted in a sentence. This phenomenon is assumed to reflect `r mcq(c(answer = "top down", "bottom up"))` processing. Important cues which facilitate ph`r fitb(answer = "onemic", width = "10")` r`r fitb(answer = "estoration", width = "10")` are LEXICAL and CONTEXTUAL cues, and co`r fitb(answer = "articulation", width = "10")` cues.

The g`r fitb(answer = "ating", width = "10")` paradigm involves identifying words from phonetic fragments of increasing length. It demonstrates the early activation of a c`r fitb(answer = "ohort", width = "10")`  (set of possible choices). The g`r fitb(answer = "ating", width = "10")` paradigm is subject to frequency and nei`r fitb(answer = "ghbourhood", width = "10")`  d`r fitb(answer = "ensity", width = "10")`  effects such that the most rapidly identified words are `r mcq(c("frequent from high-density neightbourhoods", answer = "frequent from low-density neighbourhoods", "infrequent from high-density neighbourhoods", "infrequent from low-density neighbourhoods"))`

According to Swinney's (1979) Lexical Decision study, when processing lexically ambiguous words, `r mcq(c(answer = "irrelevant meanings are temporarily activated","irrelevant meanings are permanently activated", "irrelevant meanings are not activated"))` IRRELEVANT MEANINGS ARE TEMPORARILY ACTIVATED.

`r hide("Show Answers")`

According to AUTONOMOUS models, bottom-up processes precede top-down processes, while according to INTERACTIVE models, both types of processes interact with each other.

Studies of phoneme recognition identify CATEGORICAL PERCEPTION whereby ambiguous phonemes presented in isolation are assumed to belong to a discrete category. This phenomonen is assumed to reflect BOTTOM UP processing. PHONEMIC RESTORATION referrs to the phenomenon whereby noisy phonetic material (a cough or white noise) takes on a phonetic identity when inserted in a sentence. This phenomenon is assumed to reflect TOP DOWN processing. Important cues which facilitate PHONEMIC RESTORATION are LEXICAL and CONTEXTUAL cues, and COARTICULATION.

The GATING paradigm involves identifying words from phonetic fragments of increasing length. It demonstrates the early activation of a COHORT (set of possible choices). The GATING paradigm is subject to frequency and NEIGHBOURHOOD DENSITY effects such that the most rapidly identified words are FREQUENT FROM LOW DENSITY NEIGHBOURHOODS.

According to Swinney's (1979) Lexical Decision study, when processing lexically ambiguous words, IRRELEVANT MEANINGS ARE TEMPORARILY ACTIVATED.

`r unhide()`

# Sentence production

1. Garrett's Sentence Production Model is motivated primarily by `r mcq(c(answer = "Speech errors", "Event Related Potentials", "Patterns of breakdown in aphasia"))`

2. Which of the following is NOT determined at the message level? `r mcq(c("The entities which participate in the action/event", "The action/event", "The thematic roles/relations of the entities", answer = "The syntactic structure of the sentence", "The perspective we take on the event (e.g. which entities are focused)"))`

3. Linking rules are used to `r mcq(c(answer = "map unordered arguments at the functional level onto ordered slots at the positional level", "map unordered arguments at the positional level onto ordered slots at the functional level", "map information at the message level to information at the positional level"))`

4. Lexemes are introduced `r mcq(c(answer = "at the message level", "at the functional level", "at the positional level", answer = "at the phonetic level"))`

5. The sentence "I'm a weekend for maniacs" `r mcq(c("demonstrates the separation of the functional and positional levels", answer = "demonstrates the separation of the positional and phonetic levels", "demonstrates the separation of the message and functional levels"))`

6. This is because `r mcq(c(answer = "the voicing/de-voicing of -s is clearly applied after the lexical transposition has taken place", "The voicing/de-voicing of –s is clearly applied before the lexical transposition has taken place", "The transposition and the voicing/de-voicing of –s clearly take place at the same time"))`

7. Which of the following does NOT count as evidence for the separate retrieval of metrical and segmental information; `r mcq(c("stress shift", answer = "liaison (epenthesis) eg beer-/r/-and chips, I-/j/-am hungry", "People with aphasia produce correct sound sequences without correct stress pattern"))`

8. Which of the following does NOT count as evidence for Levelt’s claim that speech production involves retrieving syllables (form the syllabary)?; `r mcq(c("Liason (epenthesis)", "Use of an before a word starting with a vowel", answer = "Perseveration or perseverative errors eg reading rist", "Aspiration phenomena (e.g. Last hour - /t/ is aspirated)"))`

`r hide("Show answers")`

1. Garrett's Sentence Production Model is motivated primarily by SPEECH ERRORS

2. Which of the following is NOT determined at the message level? THE SYNTACTIC STRUCTURE OF THE SENTENCE

3. Linking rules are used to MAP UNORDERED ARGUMENTS AT THE FUNCTIONAL LEVEL ONTO ORDERED SLOTS AT THE POSITIONAL LEVEL.

4. Lexemes are introduced AT THE PHONETIC LEVEL

5. The sentence "I'm a weekend for maniacs" DEMONSTRATES THE SEPARATION OF THE FUNCTIONAL AND POSITIONAL LEVELS.

6. This is because THE VOICING/DE-VOICING IS CLEARLY APPLIED AFTER THE LEXICAL TRANSPOSITION HAS TAKEN PLACE

7. Which of the following does NOT count as evidence for the separate retrieval of metrical and segmental information; LIAISON (EPENTHESIS), E.G. BEER-/R/-AND CHIPS, I-/J/-AM HUNGRY. THIS IS EVIDENCE FOR A CV SYLLABIC STRUCTURE.

8. Which of the following does NOT count as evidence for Levelt’s claim that speech production involves retrieving syllables (form the syllabary)?; PERSEVERATION OR PERSEVERATIVE ERRORS, E.G. READING RIST. THIS PROCESS PRESUMABLY TAKES PLACE AFTER THE SYLLABLES HAVE BEEN RETRIEVED.

`r unhide()`

# Garden paths


1. The term "garden path" describes a phenomena whereby we `r mcq(c("fail to understand a sentence completely", answer ="temporarily misanalyse the structure of a sentence", "access the wrong meaning of a vital word"))`

2. Garden paths demonstrate the existence of syntactic `r mcq(c(answer = "heuristics (dumb but fast procedures)", "holophrastics (dumb but fast procedures)", "hephaistics (dumb but fast procedures)"))`

3. For the sentence "Because Jay always jogs a mile and a half seems a short distance to him" the garden path effect arises from a `r mcq(c("tendency to close the clause boundary as soon as possible", answer = "tendency to keep open the clause boundary for as long as possible", "tendency to make a local attachment"))` 

4. According to "least effort" principles we try to build a syntactic tree `r mcq(c("with the most nodes possible", answer = "with the fewest nodes possible", "with more branches going to the right"))`.

5. According to the Trueswell study, we `r mcq(c(answer = "make predictions regarding sentence structure on hearing the verb.", "make predictions regarding sentence semantics on hearing the verb."))`. These `r mcq(c(answer = "are", "are not"))` based on the previous behaviour of the verb.

`r hide("show answers")`

1. The term "garden path" describes a phenomena whereby we TEMPORARLILY MIS-ANALYSE THE STRUCTURE OF A SENTENCE.

2. Garden paths demonstrate the existence of syntactic HEURISTICS (DUMB BUT FAST PROCEDURES)

3. For the sentence "Because Jay always jogs a mile and a half seems a short distance to him" the garden path effect arises from a TENDENCY TO KEEP OPEN THE CLAUSE BOUNDARY FOR AS LONG AS POSSIBLE.

4. According to "least effort" principles we try to build a syntactic tree WITH THE FEWEST NODES POSSIBLE.

5. According to the Trueswell study, we MAKE PREDICTIONS REGARDING SENTENCE STRUCTURE ON HEARING THE VERB. These ARE based on the previous behaviour of the verb.

`r unhide()`

# Sentence complexity

1. A sentence which is syntactically complex tends to a `r mcq(c("canonical", answer = "non-canonical"))` word order. In other words, the order of syntactic functions is not `r mcq(c(answer = "SUBJECT-VERB-OBJECT", "OBJECT-SUBJECT-VERB", "VERB-SUBJECT-OBJECT"))`.

2. A sentence which is semantically complex has a `r mcq(c("canonical", answer = "non-canonical"))`arrangement of thematic relations. For example, the patient argument is placed in `r mcq(c(answer = "Subject", "Object", "Oblique"))` position.

4. Which of the following does NOT lead to greater processing difficulty? `r mcq(c("Placing dependent clauses in the middle of a sentence", "Placing a patient in subject position", answer = "Having a conjoined Subject Noun Phrase, eg Jack and Jill", "using non-canonical word order"))`

5. Research suggests that the complexity of information stored in the lemma of the verb impacts on processing difficulty (Shapiro, Zurif & Grimshaw, 1987). Which of the following factors is NOT specified in the lemma? `r mcq(c("the subcategorisation frame", "argument structure", answer = "the word form"))`

6. Which of the following sentences will be easiest to process? `r mcq(c("the horse that the lion chased was grey", "the horse that it chased was grey", answer = "the picture that I painted was blue"))`

`r hide("show answers")`

1. A sentence which is syntactically complex tends to have a NONCANONICAL word order. In other words, the order of syntactic functions is not SUBJECT-VERB-OBJECT.

2. A sentence which is semantically complex has a NONCANONICAL arrangement of thematic relations. For example, the patient argument is placed in OBJECT position.

4. Which of the following does not lead to greater processing difficulty? HAVING A CONJOINED SUBJECT NOUN PHRASE.

5. Research suggests that the complexity of information stored in the lemma of the verb impacts on processing difficulty (Shapiro, Zurif & Grimshaw, 1987). Which of the following factors is NOT specified in the lemma? THE WORD FORM

6. Which of the following sentences will be easiest to process? THE PICTURE THAT I PAINTED WAS BLUE. NB ALL SENTENCE HAVE THE SAME STRUCTURE (OBJECT RELATIVE CLAUSE). THIS SENTENCES IS EASIER BECAUSE (A) WE CAN USE ANIMACY TO FIGURE OUT WHO DID WHAT TO WHOM, (B) WE USE A PRONOUN INSIDE TH RELATIVE CLAUSE

`r unhide()`

# Discourse processing

1. Inferences which involve making connections between sentences are called `r mcq(c(answer = "bridging inferences", "elaborative inferences"))`

2. Inferences which involve semantically 'filling in the gaps' using our world knowledge are called `r mcq(c("bridging inferences", answer = "elaborative inferences"))`

3. According to the Construction-Integration model inference involves a combination of `r mcq(c("slow activation of a large number of inferences", answer = "rapid activation of a large number of inferences", "slow activation of small subset of inferences", "rapid activation of a small subset of inferences"))` combined with `r mcq(c("slow pruning of unlikely inferences", answer = "rapid pruning of unlikely inferences"))` It is highly dependent on `r mcq(c("short-term memory", answer = "working memory", "inhibition", "attention"))` to maintain representations of discourse relationships.

4. Which of the following is NOT an experimental paradigm used to test inference-making: `r mcq(c("cued recall", "retelling the passage", "self-paced reading", answer = "elicited imitation"))`

5. How automatic is the inference making process? `r mcq(c("Only bridging inferences are generated automatically", "Only elaborative inferences are generated automatically", answer = "Both bridging and elaborative inferences are generated automatically"))`, `r mcq(c(answer = "but the former are more automatic than the latter", "but the latter are more automatic than the former"))`.

6. According to Gernsbacher and Faust (1991), and Norbury (2005), when language-impaired individuals are required to process lexically-ambiguous words, they are `r mcq(c(answer = "good at activating all potential meanings of a word", "poor at activating all potential meanings of a word"))` but `r mcq(c("good at pruning contextually-irrelevant ones", answer = "poor at pruning contextually irrelevant ones"))`.

`r hide("Show Answers")`

1. Inferences which involve making connections between sentences are called BRIDGING INFERENCES

2. Inferences which involve semantically 'filling in the gaps' using our world knowledge are called ELABORATIVE INFERENCES

3. According to the Construction-Integration model inference involves a combination of RAPID ACTIVATION OF A LARGE NUMBER OF PLAUSIBLE INFERENCES combined with RAPID PRUNING OF UNLIKELY INFERENCES. It is highly dependent on WORKING MEMORY to maintain representations of discourse relationships.

4. Which of the following is NOT an experimental paradigm used to test inference-making: ELICITED IMITATION

5. How automatic is the inference making process? BOTH BRIDGING AND ELBABORATIVE INFERENCES ARE GENERATED AUTOMATICALLY, BUT THE FORMER ARE MORE AUTOMATIC THAN THE LATTER.

6. According to Gernsbacher and Faust (1991), and Norbury (2005), when language-impaired individuals are required to process lexically-ambiguous words, they are GOOD AT ACTIVATING ALL POTENTIAL MEANINGS OF A WORD, BUT POOR AT PRUNING CONTEXTUALLY-IRRELEVANT ONES.

`r unhide()`

# Principles of learning

1. A skewed distribution is characterised by `r mcq(c(answer= "a small number of high-frequency items", "a large number of high-frequency items"))` and  `r mcq(c("a small number of low-frequency items", answer = "a large number of low-frequency items"))` 

2. Which of the following is not characterised by a skewed distribution? `r mcq(c(answer = "the distribution of scores on a psychometric assessment", "Letter frequencies", "word frequencies, e.g. the most common nouns in English", "verbs occurring in particular slots"))`

3. Which of the following distributions is better for learning? `r mcq(c(answer = "a skewed distribution", answer = "a varying distribution without skew", answer = "a condition with no variation"))`

4. Massed learning involves `r mcq(c(answer = "short intervals between learning episodes", answer = "long intervals between learning episodes"))`

5. Disributed learning involves `r mcq(c(answer = "short intervals between learning episodes", answer = "long intervals between learning episodes"))`

6. A high dosage involves `r mcq(c("few repetitions within a single clinical session", answer = "many repetitions within a single clinical session"))`

7. For many types of non-motor learning tasks, the optimal training regime consists of `r mcq(c("short regular intervals between sessions", "long regular intervals between sessions", answer = "expanding intervals between sessions"))`

8. Sleep-related memory consolidation involves `r mcq(c("the frontal lobes", answer = "the hippocampus", "the corpus callosum"))`

9. The testing effect describes the principle whereby `r mcq(c("learning is most effective when we put ourselves under time pressure", answer = "learning is most effective when we are actively involved"))`

`r hide("Show Answers")`

1. A skewed distribution is characterised by A SMALL NUMBER OF HIGH-FREQUENCY ITEMS, and A LARGE NUMBER OF LOW FREQUENCY ITEMS.

2. Which of the following is not characterised by a skewed distribution? THE DISTRIBUTION OF SCORES ON A PSYCHOMETRIC ASSESSMENT (WHICH FOLLOWS A NORMAL DISTRIBUTION)

3. Which of the following conditions is better for learning? A SKEWED DISTRIBUTION.

4. Massed learning involves SHORT INTERVALS BETWEEN LEARNING EPISODES

5. Disributed learning involves LONG INTERVALS BETWEEN LEARNING EPISODES

6. A high dosage involves MANY REPETITIONS WITHIN A SINGLE CLINICAL SESSION.

7. For many types of non-motor learning tasks, the optimal training regime consists of EXPANDING INTERVALS BETWEEN SESSIONS.

8. Sleep-related memory consolidation involves the HIPPOCAMPUS.

9. The testing effect describes the principle whereby LEARNING IS MOST EFFECTIVE WHEN WE ARE ACTIVELY INVOLVED

`r unhide()`

